app_root: .
ignored_folders:
- vendor
- log
- logs
- assets
- public
- grifts
- tmp
- bin
- node_modules
- .sass-cache
- theme
included_extensions:
- .go
- .env
- .html
- .js
- .css
build_path: tmp
build_delay: 200ns
build_target_path: "./cmd/app"
binary_name: app
command_flags: []
enable_colors: true
log_name: openshift-partner-labs-app
