---
development:
  dialect: {{envOr "DEV_DATABASE_DIALECT" "postgres"}}
  driver: {{envOr "DEV_DATABASE_DRIVER" "pgx"}}
  database: {{envOr "DEV_DATABASE_NAME" "postgres"}}
  user: {{envOr "DEV_DATABASE_USER" "postgres"}}
  password: {{envOr "DEV_DATABASE_PASSWORD" "postgres"}}
  host: {{envOr "DEV_DATABASE_HOST" "localhost"}}
  encoding: {{envOr "DEV_DATABASE_ENCODING" "utf8"}}

test:
  dialect: {{envOr "DATABASE_DIALECT" "postgres"}}
  driver: {{envOr "DATABASE_DRIVER" "pgx"}}
  database: {{envOr "TEST_DATABASE_NAME" "postgres"}}
  user: {{envOr "TEST_DATABASE_USER" "postgres"}}
  password: {{envOr "TEST_DATABASE_PASSWORD" "postgres"}}
  host: {{envOr "TEST_DATABASE_HOST" "localhost"}}
  encoding: {{envOr "TEST_DATABASE_ENCODING" "utf8"}}

production:
  dialect: {{envOr "DATABASE_DIALECT" "postgres"}}
  driver: {{envOr "DATABASE_DRIVER" "pgx"}}
  database: {{envOr "DATABASE_NAME" "postgres"}}
  user: {{envOr "DATABASE_USER" "postgres"}}
  password: {{envOr "DATABASE_PASSWORD" "postgres"}}
  host: {{envOr "DATABASE_HOST" "localhost"}}
  encoding: {{envOr "DATABASE_ENCODING" "utf8"}}