kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-partner-labs-app
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-partner-labs-app
  template:
    metadata:
      labels:
        app: openshift-partner-labs-app
    spec:
      restartPolicy: Always
      serviceAccountName: ecoengbot
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: proxy
          image: nginxinc/nginx-unprivileged
          ports:
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /etc/nginx/certs
            - name: nginx
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: openshift-partner-labs-app
          image: 'quay.io/opdev/openshift-partner-labs-app:v2.0.0-1706573666'
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: env
              readOnly: true
              mountPath: /opt/app-root/src/.env
              subPath: .env
            - name: db
              readOnly: true
              mountPath: /opt/app-root/src/database.yml
              subPath: database.yml
            - name: kubeconfig
              readOnly: true
              mountPath: /etc/.kube
            - name: osprojectignores
              readOnly: true
              mountPath: /opt/app-root/src/osprojectignores
              subPath: osprojectignores
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccount: ecoengbot
      volumes:
        - name: certs
          secret:
            secretName: cluster-wildcard-certificate
            defaultMode: 420
        - name: env
          secret:
            secretName: openshift-partner-labs-app-env
            defaultMode: 420
        - name: db
          secret:
            secretName: openshift-partner-labs-app-env
            defaultMode: 420
        - name: kubeconfig
          secret:
            secretName: oplsecrets
            defaultMode: 420
        - name: nginx
          secret:
            secretName: openshift-partner-labs-app-nginx-configs
            defaultMode: 420
        - name: osprojectignores
          configMap:
            name: osprojectignores
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600